#Speccy
#docker run wework/speccy lint https://raw.githubusercontent.com/alesgn/Spexample.Api/master/Events-simple.yaml

#ReDoc
# docker run -p 8080:80 -e SPEC_URL=https://raw.githubusercontent.com/alesgn/Spexample.Api/master/Events-simple.yaml redocly/redoc

openapi: 3.0.0
info:
  version: 4.0.0
  title: Spexample API
  description: Let us build this new awesome Spexample API v4
servers:
  - url: https://system.spexample.com/api/v4
paths:
  /events:
    get:
      summary: Retrieve events
      operationsId: get-events
      responses:
        '200': 
          description: API event by Id reponse