#Speccy
#docker run wework/speccy lint https://bitbucket.org/alesgn/spektrixapi/src/master/Events.yaml

#ReDoc
# docker run -p 8080:80 -e SPEC_URL=https://bitbucket.org/alesgn/spektrixapi/src/master/Events.yaml redocly/redoc

openapi: 3.0.0
info:
  version: 4.0.0
  title: Spektrix API
  description: Let's build this new awesome Spektrix API v4
servers:
  - url: https://system.spektrix.com/api/v4
paths:
  /events/{eventId}:
    get:
      summary: Retrieve events by eventId
      operationsId: get-event
      responses:
        '200': 
          description: API event by Id reponse