#Speccy
# docker run wework/speccy lint https://raw.githubusercontent.com/alesgn/Spexample.Api/master/Events-simple.yaml

#ReDoc
# docker run -p 8080:80 -e SPEC_URL=https://raw.githubusercontent.com/alesgn/Spexample.Api/master/Events-simple.yaml redocly/redoc

openapi: 3.0.0
info:
  version: 4.0.0
  title: Spexample API
  description: Let us build this new awesome Spexample API v4
  contact:
    name: Spexample DevRel
    email: devrel@spexample.com
    url: 'https://developer.spexample.com/'
servers:
  - url: https://system.spexample.com/api/v4
paths:
  /events/{eventId}:
    get:
      summary: Retrieve events by eventId
      operationId: get-event-by-id
      parameters:
        - name: eventId
          in: path
          description: This is the Event ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200': 
          description: API event by Id reponse