#Speccy
#docker run wework/speccy lint https://raw.githubusercontent.com/alesgn/Spexample.Api/master/Events.yaml

#ReDoc
# docker run -p 8080:80 -e SPEC_URL=https://raw.githubusercontent.com/alesgn/Spexample.Api/master/Events.yaml redocly/redoc

openapi: 3.0.0
info:
  version: 4.0.0
  title: Spexample API
  description: Let us build this new awesome Spexample API v4
servers:
  - url: https://system.spexample.com/api/v4
paths:
  /events/{eventId}:
    get:
      summary: Retrieve events by eventId
      operationsId: get-event-by-id
      parameters:
        - eventId: This is the Id of the event
          in: path
          description: Event ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200': 
          description: API event by Id reponse