#Speccy
# docker run wework/speccy lint https://raw.githubusercontent.com/alesgn/Spexample.Api/master/Specification/Customer_final.yaml

#ReDoc
# docker run -p 8080:80 -e SPEC_URL=https://raw.githubusercontent.com/alesgn/Spexample.Api/master/Specification/Customer_final.yaml redocly/redoc

openapi: 3.0.0    #version of spec this doc is compatible with
info:
  version: 4.0.0
  title: Spexample API
  description: Let us build this new awesome Spexample API v4
  contact:
    name: Spexample DevRel
    email: devrel@spexample.com
    url: 'https://developer.spexample.com/'
servers:
  - url: '{protocol}://system.spexample.com/{clientName}/api/v4'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      clientName:
        default: test154
        description: Name of the client accessing the api
paths:
  /customers:
    post:
      summary: Add a new customer to the system
      operationId: add-new-customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - name
              properties:
                title:
                  description:
                  example: "Demo Application"
                  type: "string"
                title:
                  description:
                  example: "Demo Application"
                  type: "string"
                title:
                  description:
                  example: "Demo Application"
                  type: "string"
  /customers/{customerId}:
    get:
      summary: Retrieve a customer by customerId
      operationId: get-customer-by-id
      parameters:
        - name: customerId
          in: path
          description: This is the Customer ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200': 
          description: API customer by Id reponse
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"

components:
  schemas:
    Customer:
      properties:
        id:
          type: string
          description: Customer Id
          example: '0A00000000ABCD00'
        FirstName:
          type: string
          description: Customer first name
          example: 'Homer'
        LastName:
          type: string
          description: Customer last name
          example: 'Simpson'

public string Title { get; set; }
public string FirstName { get; set;}
public string LastName { get; set; }
public string Email { get; set; }
public DateTime? BirthDate { get; set; }
public string Mobile { get; set; }
public string Phone { get; set; }