#Speccy
#docker run wework/speccy lint https://raw.githubusercontent.com/alesgn/Spexample.Api/master/Events.yaml

#ReDoc
# docker run -p 8080:80 -e SPEC_URL=https://raw.githubusercontent.com/alesgn/Spexample.Api/master/Events.yaml redocly/redoc

openapi: 3.0.0
info:
  version: 4.0.0
  title: Spexample API
  description: Let us build this new awesome Spexample API v4
servers:
- url: https://system.spexample.com:{port}/{clientName}/api/{apiVersion}
  description: Production API
  variables:
    clientName:
      # We use demo as default
      default: demo
      description: Name of client accessing the API.
    port:
      enum:
        - '8443'
        - '443'
      default: '8443'
    apiVersion:
      default: v2
      description: Version of the API. Default is `v4`
paths:
  /events/{eventId}:
    get:
      summary: Retrieve events by eventId
      operationsId: get-event-by-id
      responses:
        '200': 
          description: API event by Id reponse
    parameters:
    - name: eventId
      in: path
      description: This is the Event ID
      required: true
      schema:
        type: integer
        format: int64